import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), r'backend\.venv\Lib\site-packages'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'backend'))
os.environ['DJANGO_SETTINGS_MODULE'] = 'lms_project.settings'
import django; django.setup()
from django.db import transaction
from learning.models import Program, Semester, LearningPath, Module, Lesson, Question

instructor_id = 1
prog_id = 5
DIR = LearningPath.Difficulty

def M(path,t,s):
    return Module.objects.create(learning_path=path, title=t, description='', sort_order=s)
def L(mod,t,s):
    Lesson.objects.create(module=mod, title=t, description='', content_type=Lesson.ContentType.MARKDOWN, content_body='', duration_minutes=10, status=Lesson.Status.PUBLISHED, sort_order=s)
def QZ(mod,t,s,qs):
    les=Lesson.objects.create(module=mod, title=t, description='', content_type=Lesson.ContentType.QUIZ, content_body='', duration_minutes=5, status=Lesson.Status.PUBLISHED, sort_order=s)
    for i,q in enumerate(qs): Question.objects.create(lesson=les, question_text=q[0], option_a=q[1], option_b=q[2], option_c=q[3], option_d=q[4], correct_option=q[5], sort_order=i+1)

G = {
'calc2':[('What is integration by parts?','Product rule reversed','Chain rule reversed','Power rule','Quotient rule','a'),('What is a Taylor series?','Function representation as infinite sum','Finite polynomial','Linear approx','Quadratic approx','a'),('What is a polar coordinate?','r and theta representation','x and y','x and z','y and z','a'),('What is convergence?','Approaching a finite limit','Diverging to infinity','Oscillating','Remaining constant','a'),('What is a vector field?','Function assigning vectors to points','Scalar field','Matrix field','Tensor field','a'),('What is divergence?','Measure of vector field outflow','Measure of rotation','Gradient','Curl','a'),('What is curl?','Measure of rotation in vector field','Measure of outflow','Gradient','Divergence','a'),('What is a parametric equation?','Coordinates expressed via parameter','Cartesian equation','Linear equation','Quadratic equation','a'),('What is a sequence?','Ordered list of numbers','A function','A set','A matrix','a'),('What is a series?','Sum of sequence terms','Product of terms','Difference of terms','Sequence of terms','a')],
'web2':[('What is AJAX?','Async JavaScript and XML','A CSS framework','A database','A server','a'),('What is a SPA?','Single Page Application','Server Page App','Static Page App','System Page App','a'),('What is a REST API?','Architectural style for APIs','A database','A CSS framework','A Python library','a'),('What is JSON?','JavaScript Object Notation','Java Object Notation','JavaScript Online Network','Java Online Network','a'),('What is responsive design?','Adapts to screen sizes','Fixed layout','Desktop only','Mobile only','a'),('What is web accessibility?','Design for all users incl disabled','Fast loading','Mobile friendly','Secure connection','a'),('What is a CDN?','Content Delivery Network','Central Data Node','Code Distribution Network','Compressed Data Network','a'),('What is SEO?','Search Engine Optimisation','Server Execution Order','System Engineering Output','Software Efficiency Optimisation','a'),('What is a CMS?','Content Management System','Computer Management System','Code Management System','Communication System','a'),('What is a framework?','Pre-built code structure','A programming language','A database','A web server','a')],
'netadmin':[('What is DHCP?','Dynamic Host Configuration Protocol','Digital Host Control','Data Handling Protocol','Distributed Host Config','a'),('What is Active Directory?','Microsoft directory service','A database','A web server','A firewall','a'),('What is LDAP?','Lightweight Directory Access Protocol','Large Data Processing','Local Domain Admin','Long Distance Protocol','a'),('What is SNMP?','Simple Network Management Protocol','Secure Network Protocol','System Network Module','Serial Network Protocol','a'),('What is a proxy server?','Intermediary for client requests','A firewall','A router','A switch','a'),('What is a VPN?','Virtual Private Network','Virtual Public Network','Verified Protocol Network','Variable Port Network','a'),('What is NAT?','Network Address Translation','Network Access Tool','Node Authentication','Network Application','a'),('What is a DMZ?','Demilitarised Zone network segment','Data Management Zone','Domain Zone','Direct Memory Zone','a'),('What is QoS?','Quality of Service','Query of System','Quantity of Signal','Queue of Sessions','a'),('What is network administration?','Managing network infrastructure','Programming','Database admin','Web design','a')],
'prog1':[('What is a data type?','Classification of data values','A variable','A function','A loop','a'),('What is a pointer?','Variable storing memory address','A data type','A function','An array','a'),('What is recursion?','Function calling itself','Loop','Conditional','Assignment','a'),('What is a struct?','Composite data type grouping variables','A class','An array','A function','a'),('What is memory leak?','Memory not freed after use','Fast memory','Large memory','Shared memory','a'),('What is an array?','Collection of elements of same type','A function','A pointer','A struct','a'),('What is a linked list?','Sequence of nodes with pointers','An array','A stack','A queue','a'),('What is a stack?','LIFO data structure','FIFO data structure','Array','Tree','a'),('What is a queue?','FIFO data structure','LIFO data structure','Array','Tree','a'),('What is a hash table?','Key-value data structure','Array','Linked list','Stack','a')],
'dsa':[('What is time complexity?','Measure of algorithm runtime','Memory usage','Code length','Lines of code','a'),('What is Big O notation?','Upper bound of complexity','Lower bound','Exact bound','Average bound','a'),('What is a binary search?','Divide and conquer on sorted array','Linear search','Hash search','Tree search','a'),('What is a binary tree?','Each node has at most 2 children','A graph','An array','A stack','a'),('What is a heap?','Complete binary tree with heap property','A stack','An array','A queue','a'),('What is a graph?','Vertices connected by edges','A tree','An array','A list','a'),('What is BFS?','Breadth-First Search','Best-First Search','Binary First Search','Backward First Search','a'),('What is DFS?','Depth-First Search','Data First Search','Dynamic First Search','Distributed First Search','a'),('What is sorting?','Arranging data in order','Searching data','Storing data','Deleting data','a'),('What is hashing?','Mapping data to fixed-size values','Sorting data','Searching data','Traversing data','a')],
'oop2':[('What is a template?','Generic programming construct','A class','A function','A variable','a'),('What is a generic?','Type-parameterised code','Specific type','Concrete class','Interface','a'),('What is operator overloading?','Custom behaviour for operators','Method overloading','Inheritance','Polymorphism','a'),('What is a namespace?','Scope for identifiers','A class','A function','A variable','a'),('What is a virtual function?','Overridable function in base class','Static function','Inline function','Friend function','a'),('What is an abstract class?','Cannot be instantiated','Can be instantiated','Final class','Sealed class','a'),('What is a friend function?','Can access private members','Global function','Static function','Virtual function','a'),('What is multiple inheritance?','Class inherits from multiple bases','Single inheritance','Multilevel inheritance','Hierarchical inheritance','a'),('What is a destructor?','Cleans up object resources','Initialises object','Copies object','Creates object','a'),('What is RAII?','Resource Acquisition Is Initialisation','Return Address','Random Access','Rapid Application','a')],
'digital':[('What is a logic gate?','Basic digital circuit element','Analogue circuit','Memory unit','Processor','a'),('What is AND gate?','Output 1 only if all inputs 1','Output 1 if any input 1','Output 0 always','Output 1 always','a'),('What is a flip-flop?','Sequential logic circuit','Combinational logic','Logic gate','Adder','a'),('What is a half adder?','Adds two bits','Adds three bits','Subtracts bits','Multiplies bits','a'),('What is a multiplexer?','Selects one of many inputs','Encodes data','Decodes data','Stores data','a'),('What is a decoder?','Converts binary to output lines','Converts analog to digital','Amplifies signal','Filters signal','a'),('What is a register?','Group of flip-flops storing bits','Logic gate','Adder circuit','Multiplexer','a'),('What is a counter?','Sequential circuit counting clock pulses','Memory unit','Logic gate','Adder','a'),('What is Boolean algebra?','Algebra of binary variables','Linear algebra','Calculus','Number theory','a'),('What is a truth table?','All possible input-output combinations','Circuit diagram','Timing diagram','State diagram','a')],
'stats1':[('What is probability?','Likelihood of event occurring','Certainty of event','Event frequency','Sample statistic','a'),('What is a random variable?','Variable with numerical outcomes','Constant variable','Fixed variable','Dependent variable','a'),('What is mean?','Average of values','Middle value','Most frequent value','Range','a'),('What is median?','Middle value when sorted','Average','Most frequent','Difference','a'),('What is standard deviation?','Spread of data from mean','Average','Median','Range','a'),('What is normal distribution?','Bell-shaped probability distribution','Uniform distribution','Binomial distribution','Poisson distribution','a'),('What is correlation?','Relationship between variables','Causation','Independence','Randomness','a'),('What is a sample?','Subset of population','Entire population','Data point','Variable','a'),('What is hypothesis testing?','Testing claim about population','Collecting data','Descriptive stats','Data visualisation','a'),('What is p-value?','Probability of observed results under null','Test statistic','Confidence interval','Effect size','a')],
'attach':[('What is industrial attachment?','Workplace learning experience','Academic lecture','Online course','Research project','a'),('What is a work plan?','Schedule of attachment activities','Business plan','Project plan','Lesson plan','a'),('What is a logbook?','Daily record of activities','Textbook','Reference book','Notebook','a'),('What is a mentor?','Experienced guide at workplace','Teacher','Professor','Supervisor','a'),('What is a report?','Summary of attachment experience','Research paper','Thesis','Proposal','a'),('What is professional conduct?','Appropriate workplace behaviour','Academic rules','Legal regulations','Social norms','a'),('What is networking?','Building professional relationships','Computer networking','Social media','Job searching','a'),('What is a portfolio?','Collection of work samples','A document','A certificate','A resume','a'),('What is time management?','Organising and planning time','Working faster','Multitasking','Delegating','a'),('What is communication?','Exchanging information effectively','Writing only','Speaking only','Listening only','a')],
'cad':[('What is CAD?','Computer-Aided Design','Computer Application Development','Central Application Design','Creative Artistic Design','a'),('What is 2D modelling?','Creating flat geometric drawings','3D solid modelling','Surface modelling','Animation','a'),('What is 3D modelling?','Creating three-dimensional objects','2D drafting','Rendering','Simulation','a'),('What is a vector graphic?','Image from geometric primitives','Raster image','Bitmap image','Pixel image','a'),('What is rasterisation?','Converting vector to pixels','Converting pixels to vector','3D rendering','Animation','a'),('What is extrusion?','Extending 2D shape into 3D','Cutting material','Joining objects','Colouring surface','a'),('What is rendering?','Generating image from 3D model','Creating 2D drawing','Printing design','Exporting file','a'),('What is layering?','Organising drawing elements by layer','Grouping objects','Colouring objects','Locking objects','a'),('What is dimensioning?','Adding measurements to drawing','Creating dimensions only','Scaling object','Rotating object','a'),('What is a solid model?','Complete 3D representation','Wireframe model','Surface model','2D drawing','a')],
'advprog':[('What is concurrency?','Multiple tasks executing simultaneously','Single task','Batch processing','Sequential processing','a'),('What is a thread?','Lightweight process unit','A process','A function','A variable','a'),('What is synchronisation?','Coordinating thread execution','Single thread','Parallel execution','Serial execution','a'),('What is a semaphore?','Synchronisation primitive','A data type','A function','A variable','a'),('What is a mutex?','Mutual exclusion lock','A variable','A function','A thread','a'),('What is deadlock?','Threads waiting for each other forever','Normal execution','Fast execution','Single thread','a'),('What is a design pattern?','Reusable solution to common problem','A bug fix','A feature','A library','a'),('What is MVC?','Model-View-Controller','Multiple View Control','Main View Component','Model View Code','a'),('What is singleton?','Ensures only one instance','Multiple instances','No instances','Abstract class','a'),('What is factory pattern?','Creates objects without specifying class','Destroys objects','Copies objects','Modifies objects','a')],
'mobile':[('What is Android?','Mobile operating system','Desktop OS','Web browser','Database','a'),('What is iOS?','Apple mobile OS','Google mobile OS','Windows mobile','Linux mobile','a'),('What is a mobile SDK?','Software Development Kit for mobile','A hardware device','A mobile phone','A computer','a'),('What is an emulator?','Simulates mobile device on computer','A mobile device','A compiler','A debugger','a'),('What is an activity?','Single screen in Android','A service','A broadcast','A content provider','a'),('What is a fragment?','Reusable UI portion','An activity','A service','A layout','a'),('What is a sensor?','Detects environmental changes','A button','A screen','A battery','a'),('What is geolocation?','Device geographic location','IP address','MAC address','WiFi name','a'),('What is push notification?','Alert from server to app','Local alert','Email notification','SMS alert','a'),('What is an intent?','Messaging between Android components','A variable','A function','A class','a')],
'se2':[('What is architecture?','High-level system structure','Code implementation','Database design','UI design','a'),('What is microservices?','Independent deployable services','Monolithic app','Single service','Client-server','a'),('What is an API gateway?','Single entry point for microservices','A database','A web server','A load balancer','a'),('What is containerisation?','Packaging app with dependencies','Virtual machine','Bare metal','Cloud storage','a'),('What is CI/CD?','Continuous Integration/Deployment','Code Import','System Integration','Component Design','a'),('What is test automation?','Automated test execution','Manual testing','Code review','Debugging','a'),('What is deployment?','Releasing software to production','Development','Testing','Design','a'),('What is monitoring?','Observing system performance','Testing','Debugging','Logging','a'),('What is scalability?','System handles growing workload','Fixed capacity','Single user','Limited resources','a'),('What is code review?','Peer review of source code','Automated testing','Debugging','Documentation','a')],
'appprog2':[('What is event-driven programming?','Flow determined by events','Sequential programming','Functional programming','Logical programming','a'),('What is a callback?','Function passed as argument','A return value','A variable','A class','a'),('What is a promise?','Async operation result placeholder','A guarantee','A function','A data type','a'),('What is async/await?','Syntax for asynchronous code','Synchronous code','Sequential code','Blocking code','a'),('What is an observable?','Stream of async data','Single value','Function','Promise','a'),('What is reactive programming?','Programming with async data streams','Procedural programming','OOP','Functional','a'),('What is a web service?','Network-based application component','Web page','Database','File server','a'),('What is SOAP?','Simple Object Access Protocol','Service Oriented App','System Object Access','Standard Online API','a'),('What is GraphQL?','Query language for APIs','Database language','Markup language','Style language','a'),('What is gRPC?','High-performance RPC framework','Graphical RPC','Generic RPC','General RPC','a')],
'algo':[('What is algorithm analysis?','Studying algorithm efficiency','Writing code','Debugging','Testing','a'),('What is divide and conquer?','Breaking problem into subproblems','Brute force','Greedy','Dynamic programming','a'),('What is dynamic programming?','Solving subproblems and storing results','Recursion','Iteration','Divide and conquer','a'),('What is a greedy algorithm?','Makes locally optimal choice','Exhaustive search','Backtracking','Branch and bound','a'),('What is NP-complete?','Hardest problems in NP','Easy problems','Trivial problems','Unsolved problems','a'),('What is polynomial time?','Runtime O(n^k)','Exponential time','Factorial time','Constant time','a'),('What is reduction?','Converting one problem to another','Simplifying','Generalising','Specialising','a'),('What is approximation algorithm?','Near-optimal solution for hard problems','Exact solution','Brute force','Randomised','a'),('What is randomised algorithm?','Uses random numbers','Deterministic','Exact','Greedy','a'),('What is amortised analysis?','Average cost over sequence of ops','Worst-case analysis','Best-case analysis','Average-case analysis','a')],
'advdb':[('What is a data warehouse?','Central repository for analytics','Transactional database','Operational database','Relational database','a'),('What is NoSQL?','Non-relational database','No database','SQL variant','Query language','a'),('What is a document store?','Stores JSON-like documents','Key-value store','Graph database','Column store','a'),('What is a graph database?','Stores entities and relationships','Relational DB','Document store','Column store','a'),('What is sharding?','Horizontal partitioning of data','Vertical partitioning','Normalisation','Denormalisation','a'),('What is replication?','Copying data across servers','Deleting data','Sharding','Indexing','a'),('What is CAP theorem?','Consistency, Availability, Partition tolerance','ACID properties','BASE properties','Normal forms','a'),('What is eventual consistency?','Data consistent eventually over time','Immediate consistency','Strong consistency','Weak consistency','a'),('What is OLAP?','Online Analytical Processing','Online Transaction Processing','Online Processing','Offline Processing','a'),('What is ETL?','Extract, Transform, Load','Extract, Test, Load','Evaluate, Transform, Load','Extract, Transfer, Log','a')],
'graphics':[('What is computer graphics?','Creating images with computers','Word processing','Spreadsheets','Databases','a'),('What is a pixel?','Smallest image element','A vector','A polygon','A line','a'),('What is a vertex?','Point in 3D space','A pixel','A triangle','A texture','a'),('What is a polygon mesh?','Collection of polygons forming 3D shape','Single polygon','Line set','Point cloud','a'),('What is texture mapping?','Applying image to 3D surface','Colouring vertex','Lighting','Shading','a'),('What is a shader?','Program for rendering effects','Hardware device','Texture image','Light source','a'),('What is anti-aliasing?','Smoothing jagged edges','Removing colour','Adding colour','Blurring image','a'),('What is transformation?','Moving, rotating, scaling objects','Creating objects','Deleting objects','Colouring objects','a'),('What is a quaternion?','Represents 3D rotation','3D vector','Matrix','Complex number','a'),('What is ray tracing?','Rendering method simulating light rays','Rasterisation','Scanline','Z-buffer','a')],
'spm':[('What is a project?','Temporary endeavour with a goal','Ongoing operation','Routine task','Daily work','a'),('What is a milestone?','Significant project event','Project goal','Task','Deliverable','a'),('What is a Gantt chart?','Bar chart showing project schedule','Network diagram','Flowchart','Organisational chart','a'),('What is WBS?','Work Breakdown Structure','Workflow System','Web Service','Whole Business Strategy','a'),('What is risk management?','Identifying and mitigating project risks','Avoiding all risks','Ignoring risks','Accepting risks','a'),('What is PERT?','Program Evaluation Review Technique','Project Estimation Tool','Process Review','Performance Test','a'),('What is critical path?','Longest sequence of dependent tasks','Shortest path','Any path','Optional tasks','a'),('What is agile PM?','Iterative approach to project management','Waterfall approach','Traditional PM','Sequential PM','a'),('What is a sprint?','Time-boxed iteration in Scrum','Long phase','Release cycle','Planning phase','a'),('What is a stakeholder?','Person affected by project','Project manager','Team member','Customer','a')],
'research':[('What is research?','Systematic investigation for knowledge','Random inquiry','Opinion gathering','Casual observation','a'),('What is a hypothesis?','Testable prediction','Research question','Conclusion','Theory','a'),('What is literature review?','Survey of published research','Book review','Summary','Bibliography','a'),('What is methodology?','Research approach and methods','Research question','Data analysis','Conclusion','a'),('What is qualitative research?','Non-numerical data analysis','Numerical data','Statistical analysis','Experiments','a'),('What is quantitative research?','Numerical data analysis','Interviews','Case studies','Observations','a'),('What is sampling?','Selecting subset of population','Whole population','Random selection','Data analysis','a'),('What is a variable?','Measurable characteristic','Constant','Fixed value','Hypothesis','a'),('What is validity?','Accuracy of measurement','Consistency','Reliability','Precision','a'),('What is reliability?','Consistency of measurement','Accuracy','Validity','Precision','a')],
'ai':[('What is AI?','Machine intelligence simulating human','Natural intelligence','Human brain','Computer hardware','a'),('What is ML?','Machine learning from data','Manual learning','Hard-coded rules','Database management','a'),('What is deep learning?','Neural networks with many layers','Shallow learning','Reinforcement learning','Supervised learning','a'),('What is a neural network?','Computing system inspired by brain','Decision tree','Linear regression','Support vector machine','a'),('What is supervised learning?','Learning with labelled data','Unlabelled data','No data','Reinforcement','a'),('What is unsupervised learning?','Learning from unlabelled data','Labelled data','Reinforcement','Supervised','a'),('What is reinforcement learning?','Learning through rewards/penalties','Supervised','Unsupervised','Semi-supervised','a'),('What is a decision tree?','Tree-structured classification model','Neural network','Regression model','Clustering','a'),('What is overfitting?','Model too complex for training data','Underfitting','Poor accuracy','Slow training','a'),('What is a chatbot?','AI conversational agent','Search engine','Database','Web scraper','a')],
'stats2':[('What is regression analysis?','Modelling variable relationships','Correlation','Mean comparison','Variance analysis','a'),('What is ANOVA?','Analysis of variance','Analysis of means','Correlation','Regression','a'),('What is chi-square test?','Test for categorical data','T-test','Z-test','F-test','a'),('What is Bayesian statistics?','Probability with prior knowledge','Frequentist stats','Descriptive stats','Inferential stats','a'),('What is MLE?','Maximum Likelihood Estimation','Minimum Loss Estimator','Mean Level Estimate','Marginal Likelihood Estimate','a'),('What is confidence interval?','Range containing population parameter','Point estimate','Standard error','P-value','a'),('What is a t-test?','Compares two group means','Compares variances','Correlation test','Regression test','a'),('What is covariance?','Measure of joint variability','Measure of spread','Mean difference','Correlation','a'),('What is a distribution?','Pattern of variable values','Single value','Fixed value','Constant','a'),('What is an outlier?','Extreme value in data','Average value','Median value','Normal value','a')],
'sysprog':[('What is systems programming?','Programming OS-level software','Application programming','Web development','Database programming','a'),('What is assembly language?','Low-level programming language','High-level language','Scripting language','Markup language','a'),('What is a system call?','Interface to OS kernel','Function call','Library call','API call','a'),('What is a buffer overflow?','Writing beyond buffer bounds','Normal write','Read operation','Memory allocation','a'),('What is a file descriptor?','Handle for open file','File name','File path','File size','a'),('What is IPC?','Inter-Process Communication','Single process','Thread communication','Network communication','a'),('What is a pipe?','Unidirectional IPC channel','Bidirectional channel','Network socket','File','a'),('What is a signal?','Notification to process','Data type','Variable','Function','a'),('What is a linker?','Combines object files into executable','Compiler','Loader','Assembler','a'),('What is a loader?','Loads program into memory','Compiler','Linker','Assembler','a')],
'iot':[('What is IoT?','Internet of Things','Internet of Text','Input Output Terminal','Integration of Tools','a'),('What is a sensor?','Detects physical phenomena','Actuator','Processor','Memory','a'),('What is an actuator?','Converts signals to physical action','Sensor','Processor','Memory','a'),('What is a microcontroller?','Small computer on single IC','Desktop CPU','GPU','RAM','a'),('What is MQTT?','Message Queuing Telemetry Transport','HTTP','FTP','TCP','a'),('What is an embedded system?','Dedicated computing system','General purpose PC','Smartphone','Server','a'),('What is firmware?','Software in read-only memory','Operating system','Application','Driver','a'),('What is RFID?','Radio-frequency identification','GPS','Bluetooth','WiFi','a'),('What is a smart device?','Internet-connected device','Dumb device','Analog device','Mechanical device','a'),('What is edge computing?','Processing near data source','Cloud computing','Central computing','Distributed computing','a')],
'cyber':[('What is cybersecurity?','Protecting computer systems from attack','Building computers','Programming','Networking','a'),('What is a vulnerability?','Weakness in system','An attack','A threat','A risk','a'),('What is a threat?','Potential danger to system','A weakness','An exploit','A vulnerability','a'),('What is malware?','Malicious software','Antivirus','Firewall','Encryption','a'),('What is phishing?','Social engineering via email','Network attack','Physical attack','Database attack','a'),('What is ransomware?','Malware demanding ransom payment','Antivirus','Firewall','Encryption tool','a'),('What is DDoS?','Distributed Denial of Service','Data Delivery System','Digital Operating System','Domain Domain Service','a'),('What is social engineering?','Manipulating people for info access','Technical hack','Physical breach','Network attack','a'),('What is pentesting?','Simulated security attack','Vulnerability scan','Antivirus','Firewall config','a'),('What is incident response?','Handling security breaches','Preventing attacks','Daily monitoring','System updates','a')],
'crypto':[('What is cryptography?','Secure communication techniques','Network security','System security','Application security','a'),('What is encryption?','Converting data to ciphertext','Decryption','Hashing','Encoding','a'),('What is symmetric encryption?','Same key for encrypt/decrypt','Different keys','Public key','No key','a'),('What is asymmetric encryption?','Different keys for encrypt/decrypt','Same key','No key','Single key','a'),('What is a hash function?','One-way data mapping','Two-way encryption','Symmetric cipher','Asymmetric cipher','a'),('What is blockchain?','Distributed immutable ledger','Database','File system','Network protocol','a'),('What is a smart contract?','Self-executing contract on blockchain','Legal document','Paper contract','Digital signature','a'),('What is a digital signature?','Cryptographic verification of authenticity','Hash function','Encryption key','Password','a'),('What is PKI?','Public Key Infrastructure','Private Key Interface','Public Knowledge Integration','Primary Key Identifier','a'),('What is a certificate?','Digital identity credential','Physical certificate','License','ID card','a')],
'hci':[('What is HCI?','Human-Computer Interaction','High Computing Interface','Human Computer Integration','Hyper Connectivity Index','a'),('What is usability?','Ease of use and learnability','Aesthetic design','Functionality','Performance','a'),('What is a user interface?','Means of user-system interaction','Backend code','Database','Network','a'),('What is user experience?','Overall user satisfaction','Visual design','Functionality','Performance','a'),('What is affordance?','Visual cue suggesting use','Constraint','Feedback','Mapping','a'),('What is a heuristic?','Usability guideline','Algorithm','Data structure','Design pattern','a'),('What is prototyping?','Early model of interface','Final product','Database design','Network design','a'),('What is accessibility?','Design for all users','Fast loading','Mobile friendly','Secure','a'),('What is information architecture?','Organising content for usability','Database schema','Network topology','Code structure','a'),('What is user research?','Studying user needs and behaviours','Market research','Data analysis','Competitor analysis','a')],
'funcprog':[('What is functional programming?','Programming with pure functions','OOP','Procedural','Logical','a'),('What is immutability?','Data cannot be changed after creation','Mutable data','Variable data','Constant data','a'),('What is a pure function?','Same input always same output','Side effects','Impure function','Method','a'),('What is a lambda?','Anonymous function','Named function','Class','Module','a'),('What is a higher-order function?','Function taking/returning functions','First-order function','Method','Constructor','a'),('What is currying?','Transforming multi-arg function into chain','Partial application','Function composition','Mapping','a'),('What is map?','Apply function to each element','Filter','Reduce','Fold','a'),('What is filter?','Select elements by predicate','Map','Reduce','Sort','a'),('What is reduce?','Accumulate elements to single value','Map','Filter','Sort','a'),('What is recursion?','Function calling itself','Iteration','Loop','Condition','a')],
'kbs':[('What is a knowledge base?','Structured collection of knowledge','Database','File system','Network','a'),('What is an expert system?','AI system mimicking human expert','Database system','Operating system','File system','a'),('What is a rule base?','Set of if-then rules','Database','Knowledge graph','Neural network','a'),('What is an inference engine?','Derives conclusions from rules','Database engine','Search engine','Game engine','a'),('What is forward chaining?','Data-driven reasoning','Goal-driven reasoning','Backward chaining','Rule-based','a'),('What is backward chaining?','Goal-driven reasoning','Data-driven reasoning','Forward chaining','Rule-based','a'),('What is an ontology?','Formal representation of concepts','Database schema','Network topology','Rule set','a'),('What is a knowledge graph?','Network of entities and relationships','Database','File system','Neural network','a'),('What is fuzzy logic?','Logic with degrees of truth','Binary logic','Boolean logic','Classical logic','a'),('What is semantic web?','Web with machine-readable meaning','Web 2.0','Web 3.0','Internet of Things','a')],
'dist':[('What is a distributed system?','Multiple computers working as one','Single computer','Mainframe','Supercomputer','a'),('What is a node?','Single computer in distributed system','Network cable','Router','Switch','a'),('What is consensus?','Agreement among distributed nodes','Single node decision','Random choice','Voting','a'),('What is Paxos?','Consensus algorithm','Sorting algorithm','Search algorithm','Routing protocol','a'),('What is Raft?','Consensus algorithm for replicated logs','Routing protocol','Sorting algorithm','Encryption','a'),('What is a replica?','Copy of data on another node','Original data','Backup only','Cache','a'),('What is leader election?','Choosing coordinating node','Voting','Random choice','Round-robin','a'),('What is distributed transaction?','Transaction across multiple nodes','Local transaction','Single-node transaction','Batch transaction','a'),('What is 2PC?','Two-Phase Commit protocol','Consensus algorithm','Replication','Partitioning','a'),('What is clock sync?','Coordinating time across nodes','Network sync','Data sync','File sync','a')],
'innov':[('What is innovation?','Creating new value','Invention','Discovery','Imitation','a'),('What is technology transfer?','Moving tech from research to practice','Tech development','Tech licensing','Tech support','a'),('What is R&D?','Research and Development','Research and Design','Rapid Development','Regulatory Design','a'),('What is a patent?','Exclusive right for invention','Trademark','Copyright','License','a'),('What is a startup?','New business venture','Established company','Small business','Corporation','a'),('What is commercialisation?','Bringing product to market','Product development','Market research','Business planning','a'),('What is a prototype?','Early product model','Final product','Production model','Beta version','a'),('What is IP?','Intellectual property','Internet protocol','Input process','Integration point','a'),('What is incubation?','Supporting early-stage ventures','Manufacturing','Distribution','Marketing','a'),('What is technology readiness?','Level of tech maturity','Market readiness','Production readiness','Team readiness','a')],
'bi':[('What is business intelligence?','Data-driven decision making','Artificial intelligence','Machine learning','Data science','a'),('What is a dashboard?','Visual display of KPIs','A chart','A report','A table','a'),('What is data mining?','Discovering patterns in data','Data entry','Data storage','Data deletion','a'),('What is a KPI?','Key Performance Indicator','Key Process Input','Knowledge Performance Index','Key Product Indicator','a'),('What is OLAP cube?','Multi-dimensional data structure','Data table','Data warehouse','Data lake','a'),('What is data visualisation?','Graphical data representation','Data collection','Data storage','Data analysis','a'),('What is a scorecard?','Performance measurement tool','Dashboard','Chart','Report','a'),('What is predictive analytics?','Forecasting future outcomes','Descriptive analytics','Prescriptive analytics','Diagnostic analytics','a'),('What is a data lake?','Raw data storage repository','Data warehouse','Database','File system','a'),('What is self-service BI?','Users create own reports','IT-managed reporting','Manual reporting','External reporting','a')],
'sec':[('What is computer security?','Protecting systems from threats','Building computers','Programming','Networking','a'),('What is access control?','Restricting resource access','Data encryption','Network security','Application security','a'),('What is authentication?','Verifying user identity','Authorisation','Encryption','Logging','a'),('What is authorisation?','Determining user permissions','Authentication','Identification','Verification','a'),('What is intrusion detection?','Monitoring for security breaches','Preventing attacks','Encryption','Firewall','a'),('What is a firewall?','Network traffic filter','Antivirus','Encryption tool','Backup tool','a'),('What is IDS?','Intrusion Detection System','Intrusion Prevention System','Firewall','Antivirus','a'),('What is IPS?','Intrusion Prevention System','Intrusion Detection System','Firewall','Antivirus','a'),('What is SIEM?','Security Information and Event Management','Antivirus','Firewall','Encryption tool','a'),('What is forensics?','Investigation of security incidents','Prevention','Detection','Response','a')],
'ethics':[('What is professional ethics?','Moral principles in profession','Legal compliance','Company policy','Personal values','a'),('What is privacy?','Right to personal information control','Security','Confidentiality','Anonymity','a'),('What is intellectual property?','Creations of the mind','Physical property','Real estate','Personal property','a'),('What is copyright?','Right to reproduce original work','Patent','Trademark','License','a'),('What is a code of conduct?','Ethical guidelines for professionals','Legal document','Company policy','Technical standard','a'),('What is whistleblowing?','Reporting unethical practices','Complaint','Grievance','Feedback','a'),('What is data protection?','Safeguarding personal data','Data encryption','Data backup','Data storage','a'),('What is digital divide?','Inequality in tech access','Tech adoption','Digital literacy','Internet speed','a'),('What is green computing?','Environmentally sustainable computing','Fast computing','Cheap computing','Portable computing','a'),('What is cyber law?','Legal issues related to computing','Computer science','Network security','Data science','a')],
'audit':[('What is IS audit?','Evaluating information systems controls','Financial audit','Tax audit','Compliance audit','a'),('What is SOX?','Sarbanes-Oxley Act','Security Ops','System Control','Software License','a'),('What is a control?','Safeguard for system integrity','A check','A test','A review','a'),('What is risk assessment?','Evaluating potential threats','Risk elimination','Risk acceptance','Risk transfer','a'),('What is compliance?','Adhering to regulations','Performance','Efficiency','Quality','a'),('What is COBIT?','IT governance framework','Security tool','Audit tool','Compliance check','a'),('What is ITIL?','IT service management framework','Security standard','Audit standard','Compliance standard','a'),('What is vulnerability assessment?','Identifying system weaknesses','Penetration test','Security audit','Risk analysis','a'),('What is logging?','Recording system events','Auditing','Monitoring','Reporting','a'),('What is segregation of duties?','Dividing tasks to prevent fraud','Task automation','Centralised control','Role assignment','a')],
'advbi':[('What is big data?','Large complex datasets','Small data','Structured data','Transactional data','a'),('What is Hadoop?','Distributed processing framework','Database','Web server','Programming language','a'),('What is Spark?','Fast data processing engine','Database','Web server','Hardware','a'),('What is a data pipeline?','Automated data flow process','Data storage','Data deletion','Manual data processing','a'),('What is streaming data?','Continuous real-time data flow','Batch data','Static data','Historical data','a'),('What is a data warehouse?','Optimised for analytics','Transactional DB','Operational DB','File system','a'),('What is a data mart?','Departmental warehouse subset','Data lake','Data warehouse','Database','a'),('What is data governance?','Managing data availability and quality','Data storage','Data deletion','Data entry','a'),('What is master data?','Core business entities data','Transactional data','Historical data','Derived data','a'),('What is data quality?','Accuracy and completeness of data','Data quantity','Data speed','Data variety','a')],
'enterprise':[('What is ERP?','Enterprise Resource Planning','Executive Resource Planning','Enterprise Routing Protocol','Extended Resource Platform','a'),('What is CRM?','Customer Relationship Management','Customer Resource Management','Central Relationship Module','Critical Resource Management','a'),('What is SCM?','Supply Chain Management','System Control Module','Service Chain Management','Security Configuration Manager','a'),('What is SOA?','Service-Oriented Architecture','Software Organisation Architecture','System Operations Analysis','Service Object Architecture','a'),('What is ESB?','Enterprise Service Bus','Enterprise System Backup','Extended Service Bus','Essential Service Block','a'),('What is a monolithic app?','Single unified application','Microservices','Distributed system','Service-oriented','a'),('What is cloud ERP?','ERP on cloud infrastructure','On-premise ERP','Desktop ERP','Mobile ERP','a'),('What is a business process?','Series of steps for business goal','A software program','A business plan','A marketing strategy','a'),('What is workflow?','Task sequence in process','A data structure','An algorithm','A network path','a'),('What is integration?','Connecting different systems','Isolation','Separation','Disconnection','a')],
'multimedia':[('What is multimedia?','Combined media types','Single media type','Text only','Image only','a'),('What is audio?','Sound recording and processing','Image format','Video format','Text format','a'),('What is video?','Moving images with sound','Still image','Audio only','Animation only','a'),('What is animation?','Sequence of images creating motion','Still image','Video recording','Audio recording','a'),('What is compression?','Reducing file size','Increasing quality','Converting format','Editing content','a'),('What is a codec?','Compression/decompression algorithm','File format','Media player','Streaming service','a'),('What is streaming?','Continuous media delivery','Downloading','Uploading','Storing','a'),('What is a container format?','Wraps multiple media streams','Compression format','Codec','Player','a'),('What is resolution?','Pixel dimensions of media','File size','Bitrate','Frame rate','a'),('What is bitrate?','Data processed per second','Resolution','Frame rate','File size','a')],
'entrep':[('What is entrepreneurship?','Starting and running ventures','Working for others','Government employment','Academic research','a'),('What is a business plan?','Document outlining business strategy','Marketing plan','Financial plan','Operational plan','a'),('What is a value proposition?','Value offered to customers','Price point','Product feature','Brand name','a'),('What is a business model?','How business creates and captures value','Revenue model only','Cost structure only','Marketing strategy','a'),('What is bootstrapping?','Self-funding a business','Venture capital','Bank loan','Government grant','a'),('What is venture capital?','Investment in high-growth startups','Bank loan','Personal savings','Government funding','a'),('What is lean startup?','Build-measure-learn methodology','Traditional business','Corporate venture','Franchise','a'),('What is MVP?','Minimum Viable Product','Most Valuable Product','Maximum Value Product','Main Visual Product','a'),('What is a pitch deck?','Presentation to investors','Business plan','Marketing brochure','Annual report','a'),('What is scalability?','Business growth capability','Fixed capacity','Limited growth','Declining growth','a')],
'marketing':[('What is marketing?','Promoting and selling products','Accounting','Manufacturing','Human resources','a'),('What is a market?','Target group of consumers','A store','A factory','A country','a'),('What is segmentation?','Dividing market into groups','Mass marketing','Personal selling','Public relations','a'),('What is targeting?','Selecting market segments to serve','Mass market','Product development','Pricing strategy','a'),('What is positioning?','Brand image in consumer mind','Product placement','Price setting','Distribution','a'),('What is promotion?','Communicating product value','Product design','Pricing strategy','Distribution channel','a'),('What is branding?','Creating unique brand identity','Price setting','Product packaging','Advertising only','a'),('What is advertising?','Paid promotion of product','Public relations','Sales promotion','Personal selling','a'),('What is digital marketing?','Online marketing channels','Traditional media','Print advertising','Billboard','a'),('What is consumer behaviour?','Study of purchase decisions','Product design','Pricing strategy','Distribution','a')],
}

def add_sem(yr, sem_num, name, courses_list):
    sem = Semester.objects.create(program_id=prog_id, year_number=yr, semester_number=sem_num, name=name)
    print(f'\n{name} (sem={sem.id})')
    for title, desc, topics, proj_title, proj_steps, qk, diff in courses_list:
        p = LearningPath.objects.create(title=title, description=desc, status=LearningPath.Status.PUBLISHED, difficulty=diff, estimated_hours=0, instructor_id=instructor_id, semester=sem)
        for i, t in enumerate(topics, 1):
            mod = M(p, t, i)
            L(mod, f'Introduction to {t}', 1)
            L(mod, f'Core Concepts in {t}', 2)
            L(mod, f'Practical {t} Techniques', 3)
            L(mod, f'{t} Best Practices', 4)
            QZ(mod, f'{t} Quiz', 5, G[qk])
        mod = M(p, f'Project: {proj_title}', len(topics)+1)
        for j, s in enumerate(proj_steps, 1):
            L(mod, s, j)
        QZ(mod, f'{proj_title} Project Quiz', len(proj_steps)+1, G[qk])
        p.estimated_hours = round((len(topics)*(4*10+5) + (len(proj_steps)*10+5))/60)
        p.save(update_fields=['estimated_hours'])
        print(f'  {p.id}: {title}')

with transaction.atomic():
    add_sem(2, 2, 'Year 2 Semester 2', [
        ('SMA 2102 - Calculus II','Advanced integration, series, parametric equations, vector calculus.',['Advanced Integration','Infinite Series','Parametric Equations','Polar Coordinates','Vector Calculus','Line and Surface Integrals','Applications of Calculus'],'Calculus II Project',['Series Analysis','Parametric Modelling','Vector Problem','Applications Report'],'calc2',DIR.INTERMEDIATE),
        ('BIT 2207 - Web Design and Development II','AJAX, SPA, REST APIs, JSON, responsive frameworks, SEO.',['Advanced Web Technologies','AJAX and Dynamic Content','REST APIs and JSON','Single Page Applications','Responsive Frameworks','Web Performance Optimisation','SEO and Web Analytics'],'Web II Project',['Architecture Design','API Integration','Frontend Implementation','Performance Tuning'],'web2',DIR.ADVANCED),
        ('BIT 2204 - Network Systems Administration','DHCP, DNS, Active Directory, VPN, network monitoring.',['Network Admin Fundamentals','DHCP and IP Management','DNS Configuration','Active Directory Services','VPN and Remote Access','Network Monitoring','Network Security Admin'],'Network Admin Project',['Infrastructure Design','Service Configuration','Security Setup','Monitoring Implementation'],'netadmin',DIR.ADVANCED),
        ('BIT 2118 - Application Programming I','Memory management, pointers, data structures, file I/O in C/C++.',['App Programming Basics','Pointers and Memory','File I/O and Streams','Data Structures in C','Dynamic Memory','Recursion and Functions','Debugging and Optimisation'],'App Programming Project',['Problem Analysis','Implementation','Testing and Debugging','Optimisation'],'prog1',DIR.INTERMEDIATE),
        ('ICS 2105 - Data Structures and Algorithms','Complexity analysis, trees, graphs, hashing, sorting, searching.',['Algorithm Analysis','Recursion and D&C','Trees and BSTs','Graph Algorithms','Hashing and Hash Tables','Sorting Algorithms','Advanced Data Structures'],'DSA Project',['Problem Decomposition','Algorithm Design','Complexity Analysis','Implementation and Testing'],'dsa',DIR.INTERMEDIATE),
        ('ICS 2201 - Object Oriented Programming II','Templates, generics, operator overloading, multiple inheritance, RAII.',['Advanced OOP','Templates and Generics','Operator Overloading','Multiple Inheritance','Virtual Functions','Namespaces and Safety','RAII and Resources'],'Advanced OOP Project',['Design','Template Implementation','Polymorphic Design','Testing'],'oop2',DIR.ADVANCED),
        ('ICS 2205 - Digital Logic','Logic gates, Boolean algebra, flip-flops, counters, registers.',['Number Systems','Logic Gates and Circuits','Combinational Logic','Sequential Logic','Flip-Flops and Registers','Counters and Timers','Memory Elements'],'Digital Logic Project',['Circuit Design','Simulation','Prototype','Documentation'],'digital',DIR.INTERMEDIATE),
        ('STA 2100 - Probability and Statistics I','Probability, distributions, sampling, hypothesis testing, correlation.',['Probability','Random Variables','Distributions','Sampling and Estimation','Hypothesis Testing','Correlation and Regression','Statistical Software'],'Statistics Project',['Data Collection','Analysis','Testing','Report'],'stats1',DIR.INTERMEDIATE),
        ('BIT 2122 - Industrial Attachment','Workplace experience, professional conduct, reporting, portfolio.',['Attachment Preparation','Workplace Integration','Communication','Technical Skills','Reporting','Portfolio','Evaluation'],'Attachment Report',['Work Plan','Logbook','Technical Report','Portfolio'],'attach',DIR.INTERMEDIATE),
    ])

    add_sem(3, 1, 'Year 3 Semester 1', [
        ('BIT 2111 - Computer Aided Design','2D/3D modelling, rendering, CAD standards, engineering drawings.',['CAD Intro','2D Drafting','3D Modelling','Advanced 3D','Rendering','CAD Standards','Project Management'],'CAD Project',['Design Brief','2D Drawings','3D Model','Presentation'],'cad',DIR.INTERMEDIATE),
        ('BIT 2203 - Advanced Programming','Concurrency, threading, synchronization, design patterns, MVC.',['Concurrency','Threading','Synchronisation','Memory Management','Design Patterns','MVC Architecture','Performance'],'Advanced Prog Project',['Architecture','Implementation','Pattern Application','Analysis'],'advprog',DIR.ADVANCED),
        ('BIT 2320 - Mobile Application Development','Android/iOS, mobile SDKs, UI design, sensors, deployment.',['Mobile Platforms','Android SDK','iOS Basics','Mobile UI/UX','Sensors','Data Persistence','App Deployment'],'Mobile App Project',['App Concept','UI Implementation','Features','Testing'],'mobile',DIR.ADVANCED),
        ('BIT 2321 - Software Engineering II','Architecture, microservices, CI/CD, Docker, deployment.',['Software Architecture','Microservices','API Gateways','Docker','CI/CD Pipelines','Cloud Deployment','Monitoring'],'SE II Project',['Architecture','Implementation','CI/CD Setup','Deployment'],'se2',DIR.ADVANCED),
        ('BIT 2323 - Application Programming II','Event-driven, async, reactive programming, web services.',['Event-Driven','Async Programming','Promises','Reactive Programming','Web Services','Message Queues','Enterprise Integration'],'App Prog II Project',['System Design','Implementation','Integration','Testing'],'appprog2',DIR.ADVANCED),
        ('ICS 2301 - Design and Analysis of Algorithms','Advanced algorithms, NP-completeness, approximations.',['Algorithm Paradigms','Divide and Conquer','Dynamic Programming','Greedy Algorithms','Advanced Graphs','NP-Completeness','Approximation'],'Algorithms Project',['Analysis','Design','Complexity Analysis','Benchmarking'],'algo',DIR.ADVANCED),
        ('ICS 2404 - Advanced DBMS','Data warehousing, NoSQL, sharding, replication, CAP theorem.',['Advanced DB','Data Warehousing','NoSQL Databases','Document/Graph Stores','Sharding','Replication','Big Data'],'Advanced DB Project',['Requirements','Data Model','Implementation','Evaluation'],'advdb',DIR.ADVANCED),
        ('BIT 2325 - Computer Graphics and Animation','Rendering, transformations, shaders, animation.',['Graphics','2D Transformations','3D Pipeline','Lighting','Texture Mapping','Animation','Advanced Rendering'],'Graphics Project',['Scene Design','3D Modelling','Animation','Rendered Output'],'graphics',DIR.ADVANCED),
    ])

    add_sem(3, 2, 'Year 3 Semester 2', [
        ('BIT 2215 - Software Project Management','Planning, WBS, PERT, risk, agile, stakeholders.',['PM Fundamentals','Planning and Estimation','WBS','Scheduling and PERT/CPM','Risk Management','Agile PM','Stakeholder Management'],'PM Project',['Charter','Schedule','Risk Register','Closure'],'spm',DIR.ADVANCED),
        ('BIT 2301 - Research Methodology','Research design, literature review, methodology, academic writing.',['Intro to Research','Problem Formulation','Literature Review','Research Design','Data Collection','Data Analysis','Academic Writing'],'Research Proposal',['Problem Statement','Lit Review','Methodology','Proposal'],'research',DIR.ADVANCED),
        ('BIT 2319 - Artificial Intelligence','Search, ML, neural networks, NLP, expert systems.',['AI Fundamentals','Search and Optimisation','ML Basics','Neural Networks','NLP','Expert Systems','AI Ethics'],'AI Project',['Problem Definition','Model Selection','Implementation','Evaluation'],'ai',DIR.ADVANCED),
        ('STA 2200 - Probability and Statistics II','Regression, ANOVA, Bayesian, MLE, time series.',['Regression Analysis','ANOVA','Bayesian Statistics','MLE','Multivariate Analysis','Time Series','Statistical Modelling'],'Stats II Project',['Exploration','Model Building','Validation','Report'],'stats2',DIR.ADVANCED),
        ('ICS 2305 - Systems Programming','Assembly, system calls, IPC, signals, file systems, loaders.',['Systems Prog Overview','Assembly','System Calls','IPC','Signals and Errors','File Systems','Linkers and Loaders'],'Sys Prog Project',['Low-Level Impl','IPC Mechanisms','File System Ops','Tool Development'],'sysprog',DIR.ADVANCED),
        ('BIT 2326 - IoT and Embedded Systems','Sensors, microcontrollers, MQTT, edge computing, security.',['IoT Fundamentals','Sensors and Actuators','Microcontrollers','IoT Protocols','Data Processing','Edge Computing','IoT Security'],'IoT Project',['System Design','Hardware','Software','Deployment'],'iot',DIR.ADVANCED),
        ('BIT 2327 - Intro to Cyber Security','Threats, malware, network security, policies, incident response.',['Cyber Security','Network Security','Malware and Threats','Social Engineering','Security Policies','Incident Response','Pentesting Basics'],'Cyber Security Project',['Threat Assessment','Controls','Incident Plan','Report'],'cyber',DIR.ADVANCED),
        ('BIT 2328 - Cryptography and Blockchain','Encryption, hashing, digital signatures, blockchain, smart contracts.',['Crypto Fundamentals','Symmetric Encryption','Asymmetric Encryption','Hashing and Signatures','Blockchain','Smart Contracts','Applications'],'Blockchain Project',['Use Case','Architecture','Smart Contract','Testing'],'crypto',DIR.ADVANCED),
    ])

    add_sem(4, 1, 'Year 4 Semester 1', [
        ('BIT 2303 - Research Project','Independent research: proposal, methodology, implementation, thesis.',['Project Planning','Lit Review','Methodology','Implementation','Data Analysis','Thesis Writing','Presentation'],'Research Project',['Proposal','Methodology','Results','Thesis'],'research',DIR.ADVANCED),
        ('BIT 2305 - Human Computer Interactions','Usability, UX, prototyping, accessibility, user research.',['HCI Fundamentals','User-Centred Design','Prototyping','Usability Evaluation','Accessibility','UX Design','Interaction Design'],'HCI Project',['User Research','Prototype','Testing','Report'],'hci',DIR.ADVANCED),
        ('BIT 2400 - Intro to Functional Programming','Pure functions, immutability, lambda calculus, monads.',['FP Paradigm','Pure Functions','Lambda Calculus','Higher-Order Funcs','Recursion','Monads','Practical FP'],'FP Project',['Analysis','Pure Functions','Implementation','Testing'],'funcprog',DIR.ADVANCED),
        ('ICS 2405 - Knowledge Based Systems','Expert systems, rule-based reasoning, ontologies, knowledge graphs.',['Knowledge Representation','Rule-Based Systems','Inference Engines','Ontologies','Knowledge Graphs','Fuzzy Logic','Knowledge Acquisition'],'KBS Project',['Domain Analysis','Knowledge Base','Rule Impl','Testing'],'kbs',DIR.ADVANCED),
        ('ICS 2403 - Distributed Systems','Consensus, replication, distributed transactions, fault tolerance.',['Distributed Systems','Consensus (Paxos/Raft)','Replication','Distributed Transactions','Clock Sync','Fault Tolerance','Distributed Storage'],'Distributed Systems Project',['Design','Consensus Impl','Replication','Evaluation'],'dist',DIR.ADVANCED),
        ('HSC 2408 - Innovation and Technology Transfer','Innovation, IP, tech commercialisation, R&D.',['Innovation','Tech Transfer Process','IP Management','R&D Management','Commercialisation','Tech Readiness','Innovation Ecosystems'],'Innovation Project',['Assessment','IP Strategy','Plan','Presentation'],'innov',DIR.ADVANCED),
        ('BIT 2210 - Fundamentals of Business Intelligence','Data warehousing, OLAP, dashboards, data mining.',['BI Fundamentals','Data Warehousing','OLAP','Data Mining','Dashboards','Predictive Analytics','BI Strategy'],'BI Project',['Requirements','Data Model','Dashboard','Insights'],'bi',DIR.ADVANCED),
        ('BIT 2317 - Computer Systems Security','Access control, IDS/IPS, SIEM, forensics, risk management.',['Systems Security','Access Control','IDS/IPS','SIEM','Digital Forensics','Risk Management','Auditing'],'Systems Security Project',['Risk Assessment','Architecture','Incident Plan','Audit'],'sec',DIR.ADVANCED),
    ])

    add_sem(4, 2, 'Year 4 Semester 2', [
        ('BIT 2313 - Professional Issues in ICT','Ethics, privacy, IP, cyber law, digital divide, green computing.',['Professional Ethics','Privacy and Data Protection','IP Law','Cyber Law','Digital Divide','Green Computing','Code of Conduct'],'Professional Issues Project',['Case Analysis','Ethical Framework','Recommendations','Report'],'ethics',DIR.ADVANCED),
        ('BIT 2318 - Information System Audit','Audit frameworks, controls, risk, compliance, COBIT, ITIL.',['IS Audit','Audit Frameworks','Internal Controls','Risk-Based Auditing','Compliance','Audit Tools','Reporting'],'IS Audit Project',['Audit Plan','Control Testing','Findings','Opinion'],'audit',DIR.ADVANCED),
        ('BIT 2401 - Advanced Business Intelligence','Big data, Hadoop, Spark, streaming, data lakes, governance.',['Big Data Analytics','Hadoop Ecosystem','Apache Spark','Streaming Data','Data Lakes','Data Governance','AI Integration'],'Advanced BI Project',['Architecture','Pipeline','Analytics','Governance'],'advbi',DIR.ADVANCED),
        ('BIT 2402 - Enterprise Systems Applications and Architecture','ERP, CRM, SCM, SOA, enterprise integration, cloud ERP.',['Enterprise Systems','ERP Systems','CRM','SCM','SOA','Enterprise Integration','Cloud ERP'],'Enterprise Systems Project',['Requirements','Selection','Integration Design','Roadmap'],'enterprise',DIR.ADVANCED),
        ('ICS 2303 - Multimedia Systems and Applications','Audio, video, animation, compression, streaming.',['Multimedia','Digital Audio','Digital Video','Compression','Streaming','Multimedia Authoring','Interactive Multimedia'],'Multimedia Project',['Content Plan','Media Production','Authoring','Delivery'],'multimedia',DIR.ADVANCED),
        ('HRD 2401 - Entrepreneurship Skills','Business planning, venture capital, lean startup, MVP.',['Entrepreneurship','Opportunity Identification','Business Planning','Funding','Lean Startup','Growth and Scaling','Leadership'],'Entrepreneurship Project',['Idea Validation','Business Plan','Pitch Deck','Strategy'],'entrep',DIR.ADVANCED),
        ('HBC 2112 - Principles of Marketing','Marketing mix, segmentation, branding, digital marketing.',['Marketing Fundamentals','Segmentation and Targeting','Marketing Mix','Branding','Digital Marketing','Consumer Behaviour','Strategy'],'Marketing Project',['Market Analysis','Strategy','Campaign Plan','Metrics'],'marketing',DIR.ADVANCED),
    ])

    prog = Program.objects.get(id=prog_id)
    total = LearningPath.objects.filter(semester__program=prog).count()
    print(f'\n=== BSc IT Complete: {prog.semesters.count()} sems, {total} paths ===')
